name = "ComputedFieldTypes"
uuid = "459fdd68-db75-56b8-8c15-d717a790f88e"
authors = ["Jameson Nash <vtjnash@gmail.com>"]
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
